/**
 * Export and import.
 *
 * Data portability here means one thing: a file the user can open without this
 * app. The JSON backup is the complete user record and can be re-imported. The
 * LaTeX export compiles in any TeX distribution with no custom package. PDF is
 * produced through the browser's own print pipeline rather than by bundling a
 * PDF library, which keeps a ~300 KB dependency out of the build for a job the
 * platform already does well.
 */

import type { Problem, UserData } from '../types';

export interface BackupFile {
  format: 'open-problems-atlas-backup';
  version: 1;
  exportedAt: string;
  data: UserData;
}

export function toBackup(data: UserData): BackupFile {
  return {
    format: 'open-problems-atlas-backup',
    version: 1,
    exportedAt: new Date().toISOString(),
    data,
  };
}

export class ImportError extends Error {}

export function parseBackup(text: string): UserData {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new ImportError('That file is not valid JSON.');
  }
  const file = parsed as Partial<BackupFile>;
  if (file?.format !== 'open-problems-atlas-backup') {
    throw new ImportError('That file was not exported by Open Problems Atlas.');
  }
  if (file.version !== 1) {
    throw new ImportError(`Backup version ${String(file.version)} is not supported by this build.`);
  }
  if (!file.data || typeof file.data !== 'object') {
    throw new ImportError('The backup file has no data section.');
  }
  return file.data;
}

// ---------------------------------------------------------------------------
// LaTeX
// ---------------------------------------------------------------------------

/**
 * Escape text for LaTeX. Note the deliberate exception: `$` is left alone,
 * because the note body is written in LaTeX-flavoured markdown where $...$ is
 * how the user writes maths. Escaping it would break every formula they typed.
 */
function tex(s: string): string {
  return s
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

/** Same, but leaves $...$ spans untouched so inline maths survives. */
function texKeepMath(s: string): string {
  return s
    .split(/(\$[^$]*\$)/g)
    .map((part) => (part.startsWith('$') && part.endsWith('$') && part.length > 1 ? part : tex(part)))
    .join('');
}

export function toLaTeX(data: UserData, problems: Problem[]): string {
  const byId = new Map(problems.map((p) => [p.id, p]));
  const tracked = Object.values(data.tracked).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  const date = new Date().toISOString().slice(0, 10);

  const lines: string[] = [
    '% Generated by Open Problems Atlas.',
    '% Problem titles and descriptions are from the English Wikipedia article',
    '% "List of unsolved problems in mathematics", CC BY-SA 4.0.',
    '% Notes and status are the author\'s own.',
    '\\documentclass[11pt,a4paper]{article}',
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage[T1]{fontenc}',
    '\\usepackage{amsmath,amssymb,amsthm}',
    '\\usepackage[margin=2.5cm]{geometry}',
    '\\usepackage{hyperref}',
    '\\title{Research Journal}',
    `\\date{${date}}`,
    '\\begin{document}',
    '\\maketitle',
    '',
  ];

  if (tracked.length) {
    lines.push('\\section*{Problems being tracked}', '\\begin{itemize}');
    for (const t of tracked) {
      const p = byId.get(t.problemId);
      const title = tex(p?.title ?? t.problemId);
      const field = p ? ` \\textit{(${tex(p.field)})}` : '';
      const difficulty =
        t.perceivedDifficulty !== undefined ? `, self-rated ${t.perceivedDifficulty}/5` : '';
      lines.push(`  \\item \\textbf{${title}}${field} --- ${tex(t.state)}${difficulty}`);
    }
    lines.push('\\end{itemize}', '');
  }

  const journal = [...data.journal].sort((a, b) => a.problemId.localeCompare(b.problemId));
  if (journal.length) {
    lines.push('\\section*{Notes}', '');
    let currentProblem = '';
    for (const entry of journal) {
      if (entry.problemId !== currentProblem) {
        currentProblem = entry.problemId;
        const p = byId.get(currentProblem);
        lines.push(`\\subsection*{${tex(p?.title ?? currentProblem)}}`);
        if (p?.description) lines.push(`\\textit{${texKeepMath(p.description)}}`, '');
        if (p?.wikipediaTitle) {
          const url = `https://en.wikipedia.org/wiki/${encodeURIComponent(p.wikipediaTitle.replace(/ /g, '_'))}`;
          lines.push(`\\noindent\\small Source: \\url{${url}}\\normalsize`, '');
        }
      }
      lines.push(`\\paragraph{${tex(entry.title)}}`);
      lines.push(`\\small Last edited ${entry.updatedAt.slice(0, 10)}.\\normalsize`, '');
      lines.push(texKeepMath(entry.body), '');
    }
  }

  if (!tracked.length && !journal.length) {
    lines.push('\\noindent No problems tracked and no notes written yet.', '');
  }

  lines.push('\\end{document}', '');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------

export function toMarkdown(data: UserData, problems: Problem[]): string {
  const byId = new Map(problems.map((p) => [p.id, p]));
  const out: string[] = ['# Research journal', '', `Exported ${new Date().toISOString().slice(0, 10)}.`, ''];

  const tracked = Object.values(data.tracked).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  if (tracked.length) {
    out.push('## Tracking', '', '| Problem | Field | State | Self-rated |', '| --- | --- | --- | --- |');
    for (const t of tracked) {
      const p = byId.get(t.problemId);
      out.push(
        `| ${p?.title ?? t.problemId} | ${p?.field ?? '?'} | ${t.state} | ${
          t.perceivedDifficulty ? `${t.perceivedDifficulty}/5` : '—'
        } |`,
      );
    }
    out.push('');
  }

  for (const entry of [...data.journal].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))) {
    const p = byId.get(entry.problemId);
    out.push(`## ${entry.title}`, '', `**Problem:** ${p?.title ?? entry.problemId}  `);
    out.push(`**Last edited:** ${entry.updatedAt.slice(0, 10)}`, '', entry.body, '');
  }
  return out.join('\n');
}

// ---------------------------------------------------------------------------
// Download
// ---------------------------------------------------------------------------

export function download(filename: string, contents: string, mime: string) {
  const blob = new Blob([contents], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke on the next tick: revoking synchronously can cancel the download in
  // some browsers before it has read the blob.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const filenameStamp = () => new Date().toISOString().slice(0, 10);
